### ISSUE TITLE
`setDate` do not work with `inline = true`

### ISSUE THREAD

**Issue by gilles-crealp** [wakirin/Lightpick#51]
As you can see [here](https://jsfiddle.net/GilMar_CREALP/xud5f432/), the new date, set with `lightpick.setDate()`, is not highlighted.

**Comment by wakirin** [comment]
Thanks, I'll fix it.

**Comment by wakirin** [comment]
fixed in 1.3.3
https://jsfiddle.net/d675xtmz/

**Comment by gilles-crealp** [comment]
Thank you for the reactivity!

**Comment by gilles-crealp** [comment]
Sorry, but there is still a problem: when you choose a date outside of the current month the month is not selected.
https://jsfiddle.net/GilMar_CREALP/rs793y2c/1/

**Comment by wakirin** [comment]
@gilles-crealp you are right, check please 1.3.4

https://jsfiddle.net/ndcj1t48/

**Comment by gilles-crealp** [comment]
Your fiddle is not working.

**Comment by sinankeskin** [comment]
Hi.

I believe this issue has been fixed. Could you confirm?

Thank you.

**Comment by gilles-crealp** [comment]
No, as I mention [here](https://github.com/wakirin/Lightpick/issues/51#issuecomment-477881310), when you choose a date outside of the current month the month is not selected.

**Comment by sinankeskin** [comment]
I think I see what you mean.

You mean you are on January screen but you are picking a date from February and month screen still shows January. Right?

**Comment by gilles-crealp** [comment]
No, I think that when you select a date with `setDate` (for example January 1st 1990) the date should be displayed and not the current date (October 21st 2019)...

**Comment by sinankeskin** [comment]
Understood now.

I think I'll pass this issue to @wakirin 

Thank you.

**Comment by wakirin** [comment]
Hi @gilles-crealp,
I see where is the problem.
At the moment you can call `gotoMonth` immediately after `setDate`. Eg: https://jsfiddle.net/cso1h2qx/
I'll fix it a bit later.
Thanks.
